name: Status Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      
    - name: Create output var for results
      run: | 
        var="$(cat code-coverage-results.md)"
        echo "markdown=100% code coverage" >> $GITHUB_ENV
      
    - uses: tibdex/github-app-token@v1
      id: get_installation_token
      with: 
        app_id: 170284
        private_key: ${{ secrets.PRIVATE_KEY }}

    - uses: LouisBrunner/checks-action@v1.3.1
      with:
        token: ${{ steps.get_installation_token.outputs.token }}
        name: Test XYZ
        conclusion: ${{ job.status }}
        # conclusion: action_required
        details_url: https://josh-ops.com/
        action_url: https://josh-ops.com/posts/github-code-coverage/
        output_text_description_file: code-coverage-results.md

